### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by mrtozner** [chankyupark/fashion_docker#1]
- https://drive.google.com/file/d/1yCz6pc6qHJD2Zcz8ldDmJ3NzE8wjaiT6 
- https://drive.google.com/file/d/1oM-KrNIklN4uK14XkxGqlYcSLKKYqv7C

can you give me the updated links for the drive or the source. I would be glad if you help. Thanks

**Comment by chankyupark** [comment]
I'm sorry delayed. You can now access the files.
